name: Build Unsigned iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: '3.44.4'

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate iOS scaffold
        run: flutter create --platforms ios .

      - name: Bump iOS deployment target
        run: |
          sed -i '' "s/platform :ios, '13.0'/platform :ios, '15.1'/" ios/Podfile
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.1;/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: runner-app
          path: build/ios/iphoneos/Runner.app
